# python programming for ML

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
arr = [6, 7, 8, 9] #array
a = np.array(arr) #ndarray

In [3]:
ar = [2, 2.3, 'Hello'] #okay

In [4]:
aa = np.array(ar) #not okay, all must be of thesame dtype.
aa

array(['2', '2.3', 'Hello'], dtype='<U32')

## Types

In [5]:
type(arr)

list

In [6]:
type(a)

numpy.ndarray

In [7]:
a.dtype

dtype('int32')

In [8]:
type(aa), aa.dtype

(numpy.ndarray, dtype('<U32'))

In [9]:
#dimensions
a.ndim, aa.ndim

(1, 1)

In [10]:
# shapes
a.shape, aa.shape

((4,), (3,))

In [11]:
## multi dimensional
an1 = np.array([[1,2,3], [4,5,6]])
an1

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
print(f'Dtype: {an1.dtype}, Shape: {an1.shape}, Dimensions: {an1.ndim}')

Dtype: int32, Shape: (2, 3), Dimensions: 2


In [13]:
an2 = np.array([[1,2,3], [2,3,3], [4,1,2]])

In [14]:
an2.ndim

2

## Inbuilt Functions for creating Arrays

In [15]:
#random number 2x3
arr = np.random.random((2,3))
arr

array([[0.68265211, 0.83597087, 0.0970388 ],
       [0.78801299, 0.84572467, 0.69584441]])

In [32]:
arr = np.random.randn(2,3)
arr

array([[ 0.3726419 , -0.6335386 , -0.74509755],
       [-0.54741439, -0.5390993 ,  1.24932096]])

In [35]:
arr = np.full((2,3),5)
arr

array([[5, 5, 5],
       [5, 5, 5]])

In [38]:
arr = np.eye(3,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# zeros 3x3
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
#ones 3x3
arr = np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
#identity matrix
arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
arr = np.empty((3,3))
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Ranges

In [39]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [40]:
arr = np.arange(1,5)
arr

array([1, 2, 3, 4])

In [41]:
arr = np.arange(5,20,5)
arr

array([ 5, 10, 15])

In [50]:
arr = np.arange(2,13,2).reshape(3,2)
arr

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [53]:
arr = np.linspace(0.1,5,5)
arr

array([0.1  , 1.325, 2.55 , 3.775, 5.   ])

In [54]:
arr = np.random.randint(2,10, size=(3,3))
arr

array([[3, 7, 2],
       [3, 3, 2],
       [9, 9, 9]])

In [57]:
arr = np.random.normal(2, 1.3, size=(3,3))
arr

array([[4.22923807, 2.07529981, 2.98695576],
       [1.36015198, 5.06656272, 3.993847  ],
       [3.60980081, 1.26980533, 2.83045494]])

## Intra-operability of arrays and scalars
**Element-wise operations. same shape**

In [20]:
a = np.array([[1,2,3,4],[5,2,3,9]])
b = np.array([[4,2,1,9],[5,6,2,8]])

In [21]:
c = a + b
c

array([[ 5,  4,  4, 13],
       [10,  8,  5, 17]])

In [22]:
d = a - b
d

array([[-3,  0,  2, -5],
       [ 0, -4,  1,  1]])

In [23]:
e = a / b
e

array([[0.25      , 1.        , 3.        , 0.44444444],
       [1.        , 0.33333333, 1.5       , 1.125     ]])

In [24]:
f = a % b
f

array([[1, 0, 0, 4],
       [0, 2, 1, 1]], dtype=int32)

**Broadcasting**

In [79]:
a = np.array([[1,2,3],
              [2,1,3],
              [3,7,4]])

b = np.array([[1,2,3],
             [0,4,3]])

c = np.array([0,7,8])
d = np.array([[1,3,3],
              [2,4,3],
              [2,7,4]])

In [26]:
a + b

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [58]:
a*b

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [59]:
a + c

array([[ 1,  9, 11],
       [ 2,  8, 11],
       [ 3, 14, 12]])

In [60]:
a*c

array([[ 0, 14, 24],
       [ 0,  7, 24],
       [ 0, 49, 32]])

> broadcasting is possible if one of the array is 1 dim

In [61]:
a

array([[1, 2, 3],
       [2, 1, 3],
       [3, 7, 4]])

In [62]:
# Scalar operations
a+2

array([[3, 4, 5],
       [4, 3, 5],
       [5, 9, 6]])

In [107]:
np.add(a,2)

array([[3, 4, 5],
       [4, 3, 5],
       [5, 9, 6]])

In [63]:
a*2

array([[ 2,  4,  6],
       [ 4,  2,  6],
       [ 6, 14,  8]])

In [64]:
a^2

array([[3, 0, 1],
       [0, 3, 1],
       [1, 5, 6]], dtype=int32)

In [65]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [1.41421356, 1.        , 1.73205081],
       [1.73205081, 2.64575131, 2.        ]])

In [66]:
a**2

array([[ 1,  4,  9],
       [ 4,  1,  9],
       [ 9, 49, 16]], dtype=int32)

## Append, Insert, and stack

In [82]:
a

array([[1, 2, 3],
       [2, 1, 3],
       [3, 7, 4]])

In [83]:
d

array([[1, 3, 3],
       [2, 4, 3],
       [2, 7, 4]])

In [81]:
# a and d, row wise
np.append(a,d, axis=0)

array([[1, 2, 3],
       [2, 1, 3],
       [3, 7, 4],
       [1, 3, 3],
       [2, 4, 3],
       [2, 7, 4]])

In [84]:
#columnwise
np.append(a,d,axis=1)

array([[1, 2, 3, 1, 3, 3],
       [2, 1, 3, 2, 4, 3],
       [3, 7, 4, 2, 7, 4]])

In [85]:
#all to one row
np.append(a,d)

array([1, 2, 3, 2, 1, 3, 3, 7, 4, 1, 3, 3, 2, 4, 3, 2, 7, 4])

In [86]:
a

array([[1, 2, 3],
       [2, 1, 3],
       [3, 7, 4]])

In [88]:
# row insert
np.insert(a, 1, [2,2,2], axis=0)

array([[1, 2, 3],
       [2, 2, 2],
       [2, 1, 3],
       [3, 7, 4]])

In [90]:
#column insertion
np.insert(a, 1, [2,2,2], axis=1)

array([[1, 2, 2, 3],
       [2, 2, 1, 3],
       [3, 2, 7, 4]])

In [94]:
# stack
np.vstack((a,d))

array([[1, 2, 3],
       [2, 1, 3],
       [3, 7, 4],
       [1, 3, 3],
       [2, 4, 3],
       [2, 7, 4]])

In [95]:
np.hstack((a,d))

array([[1, 2, 3, 1, 3, 3],
       [2, 1, 3, 2, 4, 3],
       [3, 7, 4, 2, 7, 4]])

## indexing and slicing

In [67]:
# first row
a[0]

array([1, 2, 3])

In [68]:
#last row
a[-1]

array([3, 7, 4])

In [69]:
#first and second row using slicing
a[:2]

array([[1, 2, 3],
       [2, 1, 3]])

In [99]:
a[a>2]

array([3, 3, 3, 7, 4])

In [104]:
a[(a>2) & (a<7)]

array([3, 3, 3, 4])

## sort

np.sort() doesnt change the original array while a.sort() changes 

In [106]:
a

array([[1, 2, 3],
       [2, 1, 3],
       [3, 7, 4]])

In [105]:
np.sort(a)

array([[1, 2, 3],
       [1, 2, 3],
       [3, 4, 7]])

## inbuild maths function

In [70]:
np.sum(a)

26

In [71]:
np.max(a)

7

In [72]:
np.min(a)

1

In [73]:
np.corrcoef(a)

array([[ 1.        ,  0.5       ,  0.24019223],
       [ 0.5       ,  1.        , -0.72057669],
       [ 0.24019223, -0.72057669,  1.        ]])

In [74]:
np.mean(a)

2.888888888888889

In [75]:
np.std(a)

1.7284832429004493

In [76]:
a == b

C:\Users\d\AppData\Local\Temp\ipykernel_22316\160026346.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  a == b


False

In [77]:
a > arr

array([[False, False,  True],
       [ True, False, False],
       [False,  True,  True]])

In [ ]:
#

## copy

In [96]:
aa = arr.copy()

In [97]:
aa

array([[4.22923807, 2.07529981, 2.98695576],
       [1.36015198, 5.06656272, 3.993847  ],
       [3.60980081, 1.26980533, 2.83045494]])

In [98]:
arr

array([[4.22923807, 2.07529981, 2.98695576],
       [1.36015198, 5.06656272, 3.993847  ],
       [3.60980081, 1.26980533, 2.83045494]])